// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoCyberpunkRPG.Data;

#nullable disable

namespace ProjetoCyberpunkRPG.Migrations
{
    [DbContext(typeof(CyberpunkContext))]
    [Migration("20260602232316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ProjetoCyberpunkRPG.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClasseNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PVMaximo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("ProjetoCyberpunkRPG.Models.Personagem", b =>
                {
                    b.OwnsOne("ProjetoCyberpunkRPG.Models.Atributos", "Atributos", b1 =>
                        {
                            b1.Property<int>("PersonagemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Carisma")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Constituicao")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Destreza")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Forca")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Inteligencia")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Sabedoria")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PersonagemId");

                            b1.ToTable("Personagens");

                            b1.WithOwner()
                                .HasForeignKey("PersonagemId");
                        });

                    b.Navigation("Atributos")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
